### ISSUE TITLE
Is there a PCB schematic or brd file available online

### ISSUE THREAD

**Issue by parzival2** [korken89/kfly_firmware#1]
Hi,
First of all, its a nice project. I also want to learn programming STM32 based boards using Chibios and thought that looking at your code and trying it out helps. I was able to get a peek at the code but I was not able to find a KFly board schematic or brd file which I can use to order it online to be printed and assemble. I would be grateful if you can provide some information.

**Comment by korken89** [comment]
Hi, I uploaded the designs here (it's for a quite old Eagle version): https://github.com/korken89/kfly_hardware
If I remember correctly this firmware is for v3.1 of the hardware.

Hope it comes to use!

**Comment by parzival2** [comment]
Thank you.
